name: 'Setup maven settings'
description: 'Creates a settings.xml file on folder .m2 for connecting on private repositories'
inputs:
  user:
    description: 'Repository User'
    required: true
  password:
    description: 'Repository Password'
    required: true
  url:
    description: 'Repository Url'
    required: true
runs:
  using: "composite"
  steps:
   - run: echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"> <activeProfiles> <activeProfile>numih</activeProfile> </activeProfiles> <profiles> <profile> <id>numih</id> <repositories> <repository> <id>central</id> <url>https://repo1.maven.org/maven2</url> <releases><enabled>true</enabled></releases> <snapshots><enabled>true</enabled></snapshots> </repository> <repository> <id>github</id> <name>GitHub Apache Maven Packages</name> <url>${INPUT_URL}</url> <releases><enabled>true</enabled></releases> <snapshots><enabled>true</enabled></snapshots> </repository> </repositories> </profile> </profiles> <servers> <server> <id>github</id> <username>${INPUT_USER}</username> <password>${INPUT_PASSWORD}</password> </server> </servers></settings>' > ~/.m2/settings.xml
     shell: bash
   - run: cat ~/.m2/settings.xml
     shell: bash
