name: 'Setup maven settings'
description: 'Creates a settings.xml file on folder .m2 for connecting on private repositories'
inputs:
  url:
    description: 'Repository Url'
    required: true
    default: ${{ secrets.MAVEN_REPOSITORY_URL }}
  user:
    description: 'Repository User'
    required: true
    default: ${{ secrets.MAVEN_REPOSITORY_USER }}
  password:
    description: 'Repository Password'
    required: true
    default: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
runs:
  using: "composite"
  steps:
   - uses: actions/setup-java@v2
     with:
       java-version: '11'
       distribution: 'temurin'
       cache: 'maven'
   - run: echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"> <activeProfiles> <activeProfile>github</activeProfile> </activeProfiles> <profiles> <profile> <id>github</id> <repositories> <repository> <id>central</id> <url>https://repo1.maven.org/maven2</url> <releases><enabled>true</enabled></releases> <snapshots><enabled>true</enabled></snapshots> </repository> <repository> <id>github</id> <name>GitHub Apache Maven Packages</name> <url>${{ inputs.url }}</url> <releases><enabled>true</enabled></releases> <snapshots><enabled>true</enabled></snapshots> </repository> </repositories> </profile> </profiles> <servers> <server> <id>github</id> <username>${{ inputs.user }}</username> <password>${{ inputs.password }}</password> </server> </servers></settings>' > ~/.m2/settings.xml
     shell: bash
